# CSE110 Assignment 2 

This assignment is to guide in solving basic programming problems using loop in Python. 




##Write your name, student ID and theory section number below:


In [ ]:
#STUDENT NAME:
#STUDENT ID:
#CSE110 SECTION: 

## Write the code in Python for following problems:

**<font color='red'>[MUST MAINTAIN VARIABLE NAMING CONVENTIONS FOR ALL THE TASKS]</font>**

### Task 1

Write python program, which prints the following sequences of values in loops:

a)	24, 18, 12, 6, 0, -6\
b)	-10, -5, 0, 5, 10, 15, 20\
c)	18, 27, 36, 45, 54, 63\
d)	18, -27, 36, -45, 54, -63

=====================================================================

**Hints(1):** Use a while loop for solving these problems.

**Hints(2):** We are already familiar with the print() function. But when we use it to print any value it automatically adds an additional newline after each print statement.

For example:\
print(1)\
print(2)

Output:\
1\
2

=====================================================================

To solve this problem, in Python3, we can add an extra argument (end = " ") in the print function which tells the program to skip printing the additional newline.

For example:\
print(1, end =" ")\
print(2)

Output: (prints the next output right to the previous one)\
12

=====================================================================

In Task-1(a), the loop counter should be initialized at 24 and the loop should terminate when the loop counter reaches -6. The difference between the first two values is 24 - 18 = 6. So the loop counter value is getting decremented by 6 in every iteration.

For your understanding, task 1(a) code is done for you.


In [ ]:
# a) 24, 18, 12, 6, 0, -6

# initialize loop counter
counter = 24

# loop structure
while counter >= -6:
    
    #inside loop body
    if counter == -6:
        print(counter, end = "") 
    else:
        print(counter, end = ", ") 
     
    counter = counter - 6 #updating loop counter
    #inside loop body
    
#outside loop body

24, 18, 12, 6, 0, -6

In [ ]:
# b)-10, -5, 0, 5, 10, 15, 20

counter = -10

while counter <= 20:

  if counter == 20:
    print(counter, end = "")
  else:
    print(counter, end = ", ")

  counter = counter + 5


-10, -5, 0, 5, 10, 15, 20

In [ ]:
# c)18, 27, 36, 45, 54, 63

counter = 18

while counter <= 63:

  if counter == 63:
    print(counter, end = "")
  else:
    print(counter, end = ", ")

  counter = counter + 9

18, 27, 36, 45, 54, 63

**Hints for 1(d):** 

print(5 * (-1)) gives output -5\
print("-" + str(5)) gives output -5

In [ ]:
# d)18,-27, 36,-45,54,-63

counter = 18
pos = 0

while counter <= 63:

  if counter == 63:
    if(pos % 2 == 0):
      print(counter, end = "")
    else:
      print(-counter, end = "")
  else:
    if(pos % 2 == 0):
      print(counter, end = ", ")
    else:
      print(-counter, end = ", ")
  counter += 9

  pos += 1

18, -27, 36, -45, 54, -63

### Task 2
Write a Python code for the following:

1)	Ask the user to enter the name of his favorite car.\
2)	Ask the user to enter a Number

Display the name of the user’s favorite car, the number of times specified in the second step.

==========================================================

**Example 01:** If the user enters “Toyota” and 2, your program should print the name “Toyota” two times.

**Input:**\
Toyota\
2

**Output:**\
Toyota\
Toyota

==========================================================

**Example 02:** If the user enters “Veyron” and 5, your program should print the name “Veyron” five times.

**Input:**\
Veyron\
5

**Output:**\
Veyron\
Veyron\
Veyron\
Veyron\
Veyron


In [ ]:
fav_car = input('Please input your favourite car.')
num = int(input('Please enter a number'))

for i in range(0, num):
  print(fav_car)

Please input your favourite car.Veyron
Please enter a number5
Veyron
Veyron
Veyron
Veyron
Veyron


### Task 3
Write a Python code of a program that adds all numbers that are multiples of **both 7 and 9** up to 600 (including 600).

Output: 2835


In [ ]:
count = 0
value = 0

while count <= 600:
  if count % 7 == 0 and count % 9 == 0:
    value += count
  count += 1

print(value)

2835


### Task 4
Write a Python code of a program that adds all numbers that are multiples of **either 7 or 9** up to 600(including 600). \
Ensure that numbers like 63 are added only once in the sum.

Output: 42649


In [ ]:
count = 0
value = 0

while count <= 600:
  if count % 7 == 0 or count % 9 == 0:
    value += count
  count += 1

print(value)

42649


### Task 5
Write a Python code of a program that adds all numbers that are multiples of **either 7 or 9 but not both**, up to 600(including 600).

Output: 39814


In [ ]:
count = 0
value = 0

while count <= 600:
  if count % 7 == 0 and count % 9 == 0:
    pass
  elif count % 7 == 0 or count % 9 == 0:
    value += count
  count += 1

print(value)

39814


### Task 6
Write a Python code to displays all the **odd numbers** between 10 and 50.

Output: 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49


In [ ]:
#Todo
counter = 10

while counter <= 50:
  if(counter % 2 == 1):
    print(counter, end=' ')

  counter += 1

11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 

### Task 7
Write a Python code that will calculate the **value of y if the expression** of y is as follows (n is the input):  

$y = 1^2 - 2^2 +3^2 -4^2 +5^2 .........+ n^2 $


==========================================================

**Example 01:** 

**Input:**\
10

**Output:**\
-55

==========================================================

**Example 02:** 

**Input:**\
20

**Output:**\
-210



In [ ]:
#Todo
count = int(input())
pos = 1
y = 0

while pos <= count:
  if pos % 2 == 0:
    y -= pos ** 2
  elif pos % 2 == 1:
    y += pos ** 2

  pos += 1
print(y)

20
-210


### Task 8

Write a Python code of a program that asks the user to enter ten numbers then display the total and the average of **ONLY** the **odd numbers** among those ten numbers. <font color='red'>[Please do not use list for this task]</font>

==========================================================

**Example 01:** 

**Input:**\
1

2

3

4

5

6

7

8

9

10

**Output:**
Total is 25 and Average is 5.0


**Explanation:**

Total is 25 = (1+3+5+7+9) and Average is 25/5 = 5.0

==========================================================


**Example 02:** 

**Input:**\
-20

3

-5

40

-17

9

20

-8

99
  
-200

**Output:**

Total is 89 and Average is 17.8


**Explanation:**

Total is 89 = (3+(-5)+(-17)+9+99) and Average is 89/5 = 17.8



In [ ]:
total = 0
odd_count = 0
average = 0
pos = 0

while pos < 10:
  num = int(input())

  if num % 2 == 1:
    total += num
    odd_count += 1
  
  pos += 1

average = total / odd_count

print(f'Total is {total} and Average is {average}')




1
2
3
4
5
6
7
8
9
10
Total is 25 and Average is 5.0


### Task 9
Write a Python code for the following:
* Ask the user to enter a Number, N
* Display the summation of multiples of 7 up to that number (**from 1 to N inclusive**)

==========================================================

**Example01:** 

**Input:**\
50

**Output:**\
196

**Explanation:**\
7 + 14 + 21 + 28 + 35 + 42 + 49 = 196

==========================================================

**Example02:** 

**Input:**\
75

**Output:**\
385

**Explanation:**\
7 + 14 + 21 + 28 + 35 + 42 + 49 + 56 + 63 + 70 = 385





In [ ]:
N = int(input('Please Enter A Number'))
value = 1
total = 0


while value <= N:
  if value % 7 == 0 and N - 7 <= value:
    print(f' {value} = ' ,end = '')
    total += value
  elif value % 7 == 0:
    print(f' {value} +' ,end = '')
    total += value
  value += 1

print(total)

Please Enter A Number75
 7 + 14 + 21 + 28 + 35 + 42 + 49 + 56 + 63 + 70 = 385


### Task 10
Write a Python code that will read 10 numbers from the user, and then print the first number, the sum of the first 2 numbers, the sum of the first 3 numbers, and so on up to the sum of 10 numbers.

==========================================================


For example,

The user enters 10, output 10, then \
The user enters 2, (10+2) = 12, output 12, then \
The user enters 4, (10+2+4) = 16, output 16, then \
The user enters 20, (10+2+4+20) = 36, output 36, and continues till the 10$^{th}$ input


In [ ]:
count = 1
sum = 0
str_num = ""

while count <= 10:
  user_input = int(input())
  sum = sum + user_input
  if count >= 2:
    str_num += f' + {user_input}'
    print(f"The user enters {user_input},({str_num}) = {sum},output {sum}. then")
  elif count == 1:
    str_num = str(sum)
    print(f"The user enters {user_input}, output {sum}. then")

  

  count += 1

10
The user enters 10, output 10. then
2
The user enters 2,(10 + 2) = 12,output 12. then
5
The user enters 5,(10 + 2 + 5) = 17,output 17. then
24
The user enters 24,(10 + 2 + 5 + 24) = 41,output 41. then
64
The user enters 64,(10 + 2 + 5 + 24 + 64) = 105,output 105. then
2
The user enters 2,(10 + 2 + 5 + 24 + 64 + 2) = 107,output 107. then
4
The user enters 4,(10 + 2 + 5 + 24 + 64 + 2 + 4) = 111,output 111. then
6
The user enters 6,(10 + 2 + 5 + 24 + 64 + 2 + 4 + 6) = 117,output 117. then
8
The user enters 8,(10 + 2 + 5 + 24 + 64 + 2 + 4 + 6 + 8) = 125,output 125. then
2
The user enters 2,(10 + 2 + 5 + 24 + 64 + 2 + 4 + 6 + 8 + 2) = 127,output 127. then





### Task 11
Write a Python program which takes a number and prints the digits from the unit place, then the tenth, then hundredth, etc. <font color='red'>(Right to Left)</font>

<font color='red'>[Consider the input number to be an INTEGER. You are not allowed to use String indexing for solving this task]</font>

**Example:** If the user gives 32768, then print 8, 6, 7, 2, 3 

=========================================================================

**Hint (1):**  The input() function, converts the input data to String data type by default. Therefore, please type cast it to an integer before proceeding further.


**Hint  (2):** First to get the digit from the right side, we can take the remainder of the number using modulus (%) operator i.e. mod 10 to get the rightmost digit and print it. For dropping the last digit, we can perform floor division by 10 on the number and then continue the same to print the other digits as shown below.

32768 % 10 = 8 

32768 // 10 = 3276 

Then,

3276 % 10 = 6

3276 // 10 = 327 

and so on

327 % 10 = 7 

327 // 10 = 32 

32 % 10 = 2 

32 // 10 = 3 

3 % 10 = 3 

3 // 10 = 0 

Done! When the number becomes 0 you can end your loop.



In [ ]:
number = int(input())
value = 0
while(number != 0):
  value = number % 10
  print(value, end = ', ')
  number = number // 10



32768
8, 6, 7, 2, 3, 

### Task 12

Write a Python program that takes a number and prints how many digits are in that number. \
<font color='red'>[Consider the input number to be an INTEGER.]</font>

<font color='red'>[You are not allowed to use len() function]</font>

**Example:** If the user gives 9876, your program should print 4. 



**Hint:** We may keep floor dividing by ten and count how many times this can be done until the number becomes 0 as illustrated below. 

9876 // 10 = 987, count = 1 \
then, 987 // 10 = 98, count = 2 \
98 // 10 = 9, count = 3 \
9 // 10 = 0, count = 4 

Done! When the number becomes 0 your loop can end giving you the count of digits, in this case for our input of 9876, 4 digits.



In [ ]:
number = int(input())
count = 0
while(number != 0):
  count += 1
  number = number // 10

print(count)

9876
4


### Task 13
Write a Python program that takes a number from the user and prints its digits from  <font color='red'> left to right. </font>

<font color='red'>[Consider the input number to be an INTEGER. You are not allowed to use String indexing for solving this task]</font>

=========================================================================

**Example:** if the user gives 32768, then print 3, 2, 7, 6, 8 

=========================================================================

**Hint(1):**  The input() function takes the input data as String data type by default. Please convert it to an integer before starting your code for the task.

**Hint(2):**  

Step 1: First, count how many digits\
Step 2: Then, calculate 10 to the power (number of digits - 1).

Step 3 with explanation: Say, the input given by the user as in our example, 32768 has 5 digits, so calculating 10 to the power 4 gives us 10000. Then floor dividing 32768 by 10000, we can get 3.\
Proceeding further, the remainder of 32768 by 10000 (32768 % 10000) gives us 2768. This time to get 2 we need to floor divide 2768 by 1000 which is basically our 10000/10. Again, taking remainder of 2768 by 1000 gives us 768 which we then divide by 100 (i.e. 1000/10) and keep on doing this until there are no more digits left (zero).


**To summarize and clarify:**\
Loop 1: First, we count digits like our Task 12, say 5 in this case for 32768\
Loop 2: Then, we calculate 10 to the power 4 (5-1), that is 10000.\
Loop 3: Then we keep repeating the three steps of floor dividing, modulus and dividing by 10 as demonstrated below\

32768 // 10000 = 3\
32768 % 10000 = 2768 \
10000 // 10 = 1000

2768 // 1000 = 2\
2768 % 1000 = 768\
1000//10 = 100

768 // 100 = 7\
768 % 100 = 68 \
100 // 10 = 10

68 // 10 = 6\
68 % 10 = 8 \
10 // 10 = 1

8 // 1 = 8\
8 % 1 = 0 \
1 // 10 = 0

Done. Loop ends as number has become 0.

In [ ]:
number = int(input())
temp = number
count = 0
while(number != 0):
  count += 1
  number = number // 10

total_digit = 10**(count - 1)

number = temp
value = 0
while(number != 0):
  value = number // total_digit
  number = number % total_digit

  if number % total_digit != 0:
    print(value, end = ', ')
  else:
    print(value, end = '')
  total_digit //= 10


32768
3, 2, 7, 6, 8

### Task 14

Write a Python program that takes a number from the user and prints the divisors of that number and then print how many divisors were there.
<font color='red'>[The input number has to be an INTEGER]</font>

==========================================================

**Example01:** 

**Input:**\
6

**Output:**\
1, 2, 3, 6 \
Total 4 divisors.


==========================================================

**Example02:** 

**Input:**\
121

**Output:**\
1, 11, 121 \
Total 3 divisors.




In [ ]:
num = int(input())
pos = 1
divisor = 0
while pos <= num:
  if num == pos:
    print(pos, end = '')
  elif num % pos == 0:
    print(pos, end = ', ')
  pos += 1

6
1, 2, 3, 6

### Task 15
Write a Python program that takes a number and tells if it is a perfect number or not. <font color='red'>[The input number has to be an INTEGER]</font>

**Perfect Number:** An integer number is said to be a perfect number if its factors, including 1 but not the number itself, sum to the number.

==========================================================

**Example01:** 

**Input:**\
6

**Output:**\
6 is a perfect number

**Explanation:**\
6 have 4 divisors: 1, 2, 3, and 6. \
If we add all factors except itself, 6 = 1 + 2 + 3.

==========================================================


**Example02:** 

**Input:**\
28

**Output:**\
28 is a perfect number

**Explanation:**\
28 have 6 divisors: 1, 2, 4, 7, 14, and 28. \
If we add all factors except itself, 28 = 1 + 2 + 4 + 7 + 14.

==========================================================

**Example03:** 

**Input:**\
33

**Output:**\
33 is not a perfect number

**Explanation:**\
33 have 3 divisors: 1, 3, 11, and 33. \
If we add all factors except itself, 15 = 1 + 3 + 11.



In [ ]:
num = int(input())
pos = 1
sum = 0
while pos < num:
  if num % pos == 0:
    sum += pos
  pos += 1


if num == sum:
  print(f'{num} is a perfect number')
else:
  print(f'{num} is a not perfect number')

6
6 is a perfect number


### Task 16

Write a Python program that asks the user for one number and tells if it is a prime number or not. <font color='red'>[The input number has to be an INTEGER]</font>

**Prime Number:** If a number has only two divisors, (1 and itself), then it is prime. If it is divisible by more numbers, then it is not a prime.

==========================================================

**Hint:** use the divisor count from task 16. 

==========================================================

**Example01:** 

**Input:**\
11

**Output:**\
11 is a prime number

**Explanation:**\
11 has only 2 divisors: 1, and 11.

==========================================================

**Example02:** 

**Input:**\
6

**Output:**\
6 is not a prime number

**Explanation:**\
6 have 4 divisors: 1, 2, 3 and 6.






In [ ]:
num = int(input())
pos = 1
count = 0
while pos <= num:
  if num % pos == 0:
    count += 1
  pos += 1


if count == 2:
  print(f'{num} is a prime number')
else:
  print(f'{num} is a not prime number')

11
11 is a prime number


### Task 17

Write a Python program that asks the user for a quantity then takes that many numbers and prints the maximum, minimum and average of those numbers. 

**<font color='red'>[CANNOT USE MAX,MIN BUILT-IN FUNCTIONS][FOR THIS TASK YOU DO NOT NEED TO USE LISTS]</font>** 

==========================================================

**Example01:** If the user enters 5 as an input for quantity. Then enters 10, 4, -1, -100, and 1. \
Your program output should be: “Maximum 10”, “Minimum -100”, “Average is -17.2”

**Input:**\
5
10
4
-1
-100
1.

**Output:**\
Maximum 10\
Minimum -100\
Average is -17.2

**Explanation:**\
Average calculation: (10+4 + (-1) + (-100) + 1)/5 = -86/5=-17.2



In [ ]:
quantity = int(input('Please enter amount of the quantity'))
max = -99999
min = 99999
total = 0

for i in range(quantity):
  value = int(input())
  total += value
  if value >= max:
    max = value
  elif value <= min:
    min = value

average = total / quantity

print(f"Maximum {max}\nMinimum {min}\nAverage is {average}")



Please enter amount of the quantity5
10
4
-1
-100
1
Maximum 10
Minimum -100
Average is -17.2


## Task 18

Write a python program that prints a square of size N using + where N will be given as input.

=======================================

**Sample Input**
5

**Sample Output**<br>
+++++<br>
+++++<br>
+++++<br>
+++++<br>
+++++<br>


=======================================

**Sample Input**
3

**Sample Output**<br>
+++<br>
+++<br>
+++<br>

In [ ]:
num = int(input())

for i in range(num):
  for j in range(num):
    print('+', end='')
  print()

5
+++++
+++++
+++++
+++++
+++++


### Task 19

Write a python program that prints a rectangle of size M (height/line numbers) and N(length/column numbers) using incrementing numbers where M,N will be given as input.

===================================

**Sample Input**
4,6

**Sample Output**<br>
123456<br>
123456<br>
123456<br>
123456<br>


===================================


**Sample Input**
3,2

**Sample Output**<br>
12<br>
12<br>
12<br>


In [ ]:
row = int(input())
column = int(input())

for i in range(1, row + 1):
  for j in range(1, column + 1):
    print(j, end='')
  print()

4
6
123456
123456
123456
123456


### Task 20

Write a python program that prints a right angled triangle of height N using incrementing numbers where N will be given as input.

====================================

**Sample Input**
4

**Sample Output**<br>
1<br>
12<br>
123<br>
1234<br>

====================================

**Sample Input**
5

**Sample Output**<br>
1<br>
12<br>
123<br>
1234<br>
12345<br>

In [ ]:
num = int(input())

for i in range(1, num + 1):
  for j in range(1, i + 1):
    print(j, end='')
  print()

4
1
12
123
1234


## Optional Tasks (21 -26) [Ungraded]

### Task 21

Write a python program that prints all the fibonacci number from 0 to N where N will be given. 

**A Fibonacci number is a number which is the summation of its previous two fibonacci number.**

First two fibonacci number are 0 and 1. So the 3rd Fib will be 0+1=1, 4th Fib will be 1+1=2, 5th Fib will be 1+2=3 and so on.

==============================

**Sample Input**<br>
10

**Sample Output**<br>
0 1 1 2 3 5 8

==============================


**Sample Input**<br>
15

**Sample Output**<br>
0 1 1 2 3 5 8 13

In [5]:
N = int(input())

first_fib = 0
second_fib = 1
temp = 0
print(first_fib, end = ' ')
print(second_fib, end = ' ')

fib_value = 0
while first_fib + second_fib <= N:
  fib_value = first_fib + second_fib
  print(fib_value, end = ' ')
  first_fib = second_fib
  second_fib = fib_value




15
0 1 1 2 3 5 8 13 

### Task 22

Write a python program that converts a Decimal Integer number to a Binary Number. 

**A decimal can be converted to a binary number by keeping track of the remainders after each division of that number by 2. **

================================

For example, to convert 10 to a binary number, we can follow the following approach

10/2 = 5 (Remainder 0) 
<br>5/2 = 2 (Remainder 1) 
<br>2/2 = 1 (Remainder 0) 
<br>1/2 = 0 (Remainder 1) 

Take the remainders from bottom to top, which is, 1010. Binary of 10 is 1010.

**Sample Input** <br>
10

**Sample Output**<br>
1010

================================

For example, to convert 13 to a binary number, we can follow the following approach

13/2 = 6 (Remainder 1) 
<br>6/2 = 3 (Remainder 0) 
<br>3/2 = 1 (Remainder 1) 
<br>1/2 = 0 (Remainder 1) 

Take the remainders from bottom to top, which is, 1101. Binary of 13 is 1101.

**Sample Input** <br>
13

**Sample Output**<br>
1101

In [16]:
dec_int = int(input())
bin_str = ""
while dec_int > 0:
  bin_num = dec_int % 2
  bin_str = str(bin_num) + bin_str
  dec_int //= 2

print(bin_str, end = '')

13
1101

### Task 23

Write a python program that converts a Binary number to a Decimal Integer Number. 

**A binary number can be converted to its corresponding decimal number by multiplying each binary digit with a power of 2 where the power denotes the position of the binary digit**

========================================

For example, to convert 1010, we can do this -


$2^{3}$ x 1 + $2^{2}$ x 0 + $2^{1}$ x 1 + $2^{0}$ x 0 = 10


**Sample Input** <br>
1010

**Sample Output** <br>
10

========================================

For example, to convert 1101, we can do this -


$2^{3}$ x 1 + $2^{2}$ x 1 + $2^{1}$ x 0 + $2^{0}$ x 1 = 13


**Sample Input** <br>
1101

**Sample Output** <br>
13

In [25]:
bin_num = input()
product = 0
for i in range(0, len(bin_num)):
  product += 2**(len(bin_num) - 1 - i) * int(bin_num[i])
print(int(product))

1101
13


### Task 24

Take five numbers from the user and find the minimum and the average of **only the even** numbers entered by the user. [If the user enters odd numbers ignore them] 

**<font color='red'>[CANNOT USE MAX,MIN BUILT-IN FUNCTIONS] [FOR THIS TASK YOU DO NOT NEED TO USE LISTS]</font>** 

Assume, the first input is always an even number.

============================================================

**Example01:** If the user enters 10, 4, -1, -100, and 1. \
Output: “Minimum -100”, “Average is 28.66667”

**Input:**\
10

4

-1

-100

1

**Output:**\
Minimum -100\
Average is 28.66667

**Explanation:**\
Average calculation: (10+4 + (-100))/3 = -86/3=-28.66667

============================================================

**Example02:** If the user enters 2, 10, 1, 21, and 3. \
Output: Minimum 2”, “Average is 6.0”

**Input:**\
2

10

1

21

3

**Output:**\
Minimum 2\
Average is 6.0

**Explanation:**\
Average calculation: (2+10)/2 = 12/2= 6





In [30]:
min = 99999
total = 0
count = 0

for i in range(0, 5):
  num = int(input())

  if num % 2 == 0:
    total += num
    count += 1
    if num <= min:
      min = num

average = total / count
print(f'Minimum {min}\nAverage is {round(average, 5)}')

2
10
1
21
3
Minimum 2
Average is 6.0


### Task 25

Write a Python code for the following:
* Ask the user to enter a number, N (Total number of inputs to be taken). Assume that the user will never enter the first number as zero.
* Take N number of inputs
* Prints out the product of all the numbers read

For example, if the first input is 4, then the program has to read in four numbers from the user and print the product of these four numbers. 

=========================================================================

**Example01:**

**Input:**\
5 

10 

6 

4 

2 

1 

**Output:**\
480

**Explanation:**\
5 is the total number of inputs taken. Then, the calculation should be 10 X 6 X 4 X 2 X 1 = 480 







In [34]:
iteration = int(input())
product = 1

for i in range(iteration):
  num = int(input())
  product = product * num
print(f'{product}')

5
10
6
4
2
1
480


### Task 26
Ask the user for a range (a starting number and an ending number). 
**Count** how many numbers are prime numbers and how many numbers are perfect numbers between that range and **print** those numbers. 


=========================================================================

**Hint (1):** Declare two strings/lists to store the prime and perfect numbers. Inside the iteration store the values of the prime and perfect numbers in the pre- declared variables.

**Hint (2):**


ans = "Prime numbers: "\
prime_value = 11
ans = ans + str(prime_value) + " "\
print(ans)

ans = ans + str(13) + " "\
print(ans)

*Output:*

Prime numbers: 11 \
Prime numbers: 11 13 

=========================================================================

**Example:**between 2 and 6, there are 3 prime numbers (2, 3, 5) and 1 perfect number (6). 

**Input:**\
2

6

**Output:**\
Between 2 and 6,\
Found 3 prime numbers \
Found 1 perfect number\
Prime numbers: 2  3  5 \
Perfect numbers: 6 



In [47]:
starting_num = int(input())
ending_num = int(input())

perfect_num = ""
prime_num = ""

for num in range(starting_num, ending_num + 1):
  prime_count = 0
  perfect_count = 0
  pos = 1
  while pos <= num:
    if num % pos == 0 and pos < num:
      perfect_count += pos
    if num % pos == 0:
      prime_count += 1
    pos += 1

  if perfect_count == num:
    perfect_num += " " + str(num)
  if prime_count == 2:
    prime_num += " " + str(num)

print('Prime numbers:{0}\nPerfect numbers:{1}'.format(prime_num, perfect_num))

2
6
Prime numbers: 2 3 5
Perfect numbers: 6
